### ISSUE TITLE
Getting following error:

### ISSUE THREAD

**Issue by surajajency** [zVPS/zvps-netbeans-phpunit-watcher#3]
Please Let me know how to fix this

![screen shot 2015-01-30 at 4 20 05 pm](https://cloud.githubusercontent.com/assets/1841224/5974521/3f7ae810-a89b-11e4-9e31-b11eb36c2938.png)

**Comment by Caffe1neAdd1ct** [comment]
Hi @surajajency 

This may be due to netbeans sending out updates to the php project plugin, unfortunately the php project plugin doesn't provide a comprehensive api so i'm having to rebuild the plugin after every php project release (called relying on an implementation version).

I'll give this a test and get back to you.

**Comment by Caffe1neAdd1ct** [comment]
Hi @surajajency 

Have you downloaded an updated version of netbeans without the php project pre-installed?

Make sure to update using either the `HTML & PHP` installer or the `All` installer.

**Comment by surajajency** [comment]
Thank you for response.
I have installed the latest 8.0.2 version of netbeans. Hope this helps.

**Comment by gferrantelli** [comment]
Hi all,

I'm experiencing the same problem!  I'm using Netbeans 8.0.2 with PHP & HTML Bundle.

thanks in advance

**Comment by Caffe1neAdd1ct** [comment]
Hi @gferrantelli 

Just having a look into this now, i built with an upgraded version of 8.0.1 which might not be the same as a clean installed 8.0.2 install.

**Comment by Caffe1neAdd1ct** [comment]
@surajajency @gferrantelli 

Could you try the nbm files here: https://github.com/zVPS/zvps-netbeans-phpunit-watcher/tree/master/nbm

Click through to them and click "Raw" to download the file. Let me know if any of them allow you to install the plugin please.

**Comment by gferrantelli** [comment]
Hi,
thanks, it works!!!Perfect!!! I opened a topic on NB PHP Forum about this issue, can I link your new nbm in thatdiscussio, so that other people can use it?

Thanks in advance!!!

**Comment by Caffe1neAdd1ct** [comment]
@gferrantelli,

Please feel free, i've been looking for ways to get round this
implementation version issue for a while.. Perhaps someone on the NB forum
will know more about it...

**Comment by tmysik** [comment]
BTW I just created a pull request with proper module implementation (to avoid implementation dependencies etc.)

**Comment by MarkusRodler** [comment]
The current version on the [Plugin Portal](http://plugins.netbeans.org/plugin/53978/phpunit-watcher) also throws a version error like the screenshot before. 
The bugfix from @tmysik works if anyone builds the nbm from source.
Maybe someone can update the Plugin Portal with the bugfix version?

**Comment by Caffe1neAdd1ct** [comment]
Sure, after the holidays I'll repackage and update the plugin portal

**Comment by MarkusRodler** [comment]
:+1: thanks a lot

**Comment by fanphp** [comment]
Hi,
news about the NB v8.1 fix for this really really awsome plugin?? :+1: 

Thanks in advance!!

**Comment by tmysik** [comment]
@fanphp 

> news about the NB v8.1 fix

What exactly do you mean?

**Comment by fanphp** [comment]
When I try to install this plugin, I get this error:

![schermata da 2016-01-07 11-24-18](https://cloud.githubusercontent.com/assets/16243659/12168260/4f619bfe-b531-11e5-9ac2-935aeb6467df.png)

Thanks!

**Comment by tmysik** [comment]
@fanphp I see. Yes, new version of plugin is needed // CC @Caffe1neAdd1ct

**Comment by Caffe1neAdd1ct** [comment]
Just setting up my dev environment and i'll get this up on the plugin portal asap.

Need to test the changes made by the last pull request then it'll be available again :+1:

**Comment by Caffe1neAdd1ct** [comment]
Please try installing/updating from the plugin portal or from https://github.com/zVPS/zvps-netbeans-phpunit-watcher/blob/master/nbm/org-zvps-phpunitwatcher-8.1-stable.nbm

**Comment by fanphp** [comment]
hi,
it works! Thanks!

**Comment by Caffe1neAdd1ct** [comment]
No problem, thanks for getting back! I'll mark as closed.
